<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6BOD738" failures="1" tests="8" name="com.adactin.base.Testng_Runner" time="25.714" errors="0" timestamp="2022-07-31T16:40:43 IST" skipped="3">
  <testcase classname="com.adactin.base.Testng_Runner" name="adactin_retry" time="0.997">
    <skipped/>
  </testcase> <!-- adactin_retry -->
  <system-out/>
  <testcase classname="com.adactin.base.Testng_Runner" name="adactin_retry" time="1.668">
    <skipped/>
  </testcase> <!-- adactin_retry -->
  <system-out/>
  <testcase classname="com.adactin.base.Testng_Runner" name="adactin_retry" time="1.092">
    <failure message="expected [https://adactinhotelapp.com/SearchHotel.php] but found [https://adactinhotelapp.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://adactinhotelapp.com/SearchHotel.php] but found [https://adactinhotelapp.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.adactin.base.Testng_Runner.adactin_retry(Testng_Runner.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- adactin_retry -->
  <system-out/>
  <testcase classname="com.adactin.base.Testng_Runner" name="adactin_retry" time="12.311">
    <skipped/>
  </testcase> <!-- adactin_retry -->
  <system-out/>
  <testcase classname="com.adactin.base.Testng_Runner" name="adactin_login" time="3.124"/>
  <system-out/>
  <testcase classname="com.adactin.base.Testng_Runner" name="select_Hotel" time="2.948"/>
  <system-out/>
  <testcase classname="com.adactin.base.Testng_Runner" name="payment" time="2.216"/>
  <system-out/>
  <testcase classname="com.adactin.base.Testng_Runner" name="close_page" time="1.358"/>
  <system-out/>
</testsuite> <!-- com.adactin.base.Testng_Runner -->
